name: Daily Stock Data Crawler

on:
  schedule:
    # 每天 UTC 时间 10:00 运行 (北京时间 18:00)
    - cron: '30 7 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  spiderdata:
    runs-on: ubuntu-latest

    env:
      SEATABLE_API_TOKEN: ${{ secrets.SEATABLE_API_TOKEN }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install DrissionPage seatable-api
        
    - name: Run stock crawler
      run: python main.py
      
