name: Stock Data Crawler

on:
  schedule:
    - cron: '0 8 * * *'  # 每天 UTC 时间 8:00 (北京时间 16:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: |
          pip install DrissionPage seatable-api

      - name: Run stock crawler
        env:
          SEATABLE_API_TOKEN: ${{ secrets.SEATABLE_API_TOKEN }}  # 使用GitHub Secrets
        run: python stock_crawler.py  # 确保文件名匹配您的脚本
